[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "python-skeleton"
dependencies = []

requires-python = ">= 3.12"

authors = [
  {name = "John Doe", email = "john.doe@example.com"},
]

description = "Quickstarter for modern python projects."

license = {file = "LICENSE"}

[project.scripts]
python_skeleton_cli = "python_skeleton:main"
